root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/flowcontrol"
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "sql"]
exclude_dir = ["build", "tmp", "vendor", "web/static"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"
send_interrupt = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true 