root = "."
tmp_dir = "tmp"

[build]
# Pre-build commands
pre_cmd = [
    "go mod vendor",
    "go mod tidy",
    "swag init -g cmd/flowcontrol/main.go --parseDependency --parseInternal"
]
# Build command
cmd = "go build -o ./tmp/main ./cmd/flowcontrol"
bin = "tmp/main"
full_bin = "./tmp/main"
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html", "sql", "json"]
# Exclude directories
exclude_dir = ["build", "tmp", "vendor", "web/static", "docs"]
include_dir = []
exclude_file = []
# Build delay in milliseconds
delay = 1000
stop_on_error = true
log = "air.log"
send_interrupt = true
# Kill process before starting new one
kill_delay = "0s"
rerun = false
rerun_delay = 500

[log]
time = true
main_only = false

[screen]
clear_on_rebuild = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true 