services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file: .env.staging
    environment:
      APP_PORT: "8080"
      CGO_ENABLED: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
      CONFIG_FILE: /app/config.json
      DB_PATH: /app/data/flows.db
      DOCKER_BUILDKIT: "1"
      ENVIRONMENT: staging
      GO_ENV: staging
      LOG_FILE: /app/logs/flow-control.log
      LOG_FORMAT: json
      LOG_LEVEL: debug
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      WEBHOOK_PORT: "9001"
      GODEBUG: "netdns=go+4,http2server=0,ipv6=0"
      GOHOSTRESOLVER: "1"
      GO_IPV6_DISABLED: "1"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    ports:
      - "8080:8080"
    networks:
      - flow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-4", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  webhook:
    image: almir/webhook
    volumes:
      - ./config/hooks.json:/etc/webhook/hooks.json
      - ./scripts:/app/scripts
    environment:
      - WEBHOOK_PORT=${WEBHOOK_PORT:-9001}
      - WEBHOOK_HOST=0.0.0.0
      - GODEBUG=netdns=go+4,http2server=0,ipv6=0
      - GOHOSTRESOLVER=1
      - GO_IPV6_DISABLED=1
    command: -hooks /etc/webhook/hooks.json -verbose -port ${WEBHOOK_PORT:-9001} -ip 0.0.0.0 -urlprefix ""
    ports:
      - "9001:9001"
    networks:
      - flow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-4", "-f", "-o", "/dev/null", "-w", "'%{http_code}'", "-s", "http://localhost:9001/hooks/deploy", "||", "test", "$$?", "==", "22", "-o", "$$?", "==", "7", "-o", "$$?", "==", "28"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

networks:
  flow-network:
    driver: bridge