services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file: .env.staging
    environment:
      - GO_ENV=staging
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "${APP_PORT:-8080}:8080"
    network_mode: host
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  webhook:
    image: almir/webhook
    volumes:
      - ./config/hooks.json:/etc/webhook/hooks.json
      - ./scripts:/app/scripts
    ports:
      - "${WEBHOOK_PORT:-9000}:9000"
    command: -hooks /etc/webhook/hooks.json -verbose
    network_mode: host
    restart: unless-stopped

networks:
  flow-network:
    name: flow-network
    external: true 