version: '3.8'

services:
  dev:
    image: golang:1.22.9-alpine
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go
    ports:
      - "8080:8080"
    command: sh -c "
      apk add --no-cache gcc musl-dev sqlite-dev && 
      go install github.com/cosmtrek/air@v1.49.0 && 
      go install github.com/swaggo/swag/cmd/swag@latest &&
      go mod download &&
      go mod tidy &&
      go mod download golang.org/x/text &&
      swag init -g cmd/flowcontrol/main.go --parseDependency --parseInternal &&
      air -c .air.toml"
    environment:
      - GO_ENV=development
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/go/cache
      - CONFIG_FILE=/app/config.json
      - CGO_ENABLED=1
      - CGO_CFLAGS=-D_FILE_OFFSET_BITS=64

  test:
    image: golang:1.22.9-alpine
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - GO_ENV=test
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/go/cache
      - CGO_ENABLED=1
      - CGO_CFLAGS=-D_FILE_OFFSET_BITS=64
    command: sh -c "
      apk add --no-cache gcc musl-dev sqlite-dev make && 
      go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest &&
      go mod download &&
      go mod tidy &&
      go test -v ./..."

volumes:
  go-cache: