version: '3.8'

services:
  dev:
    image: golang:1.22.1-bullseye
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go
    ports:
      - "8080:8080"
    command: sh -c "
      apt-get update && apt-get install -y sqlite3 libsqlite3-dev && 
      go install github.com/cosmtrek/air@v1.49.0 && 
      go install github.com/swaggo/swag/cmd/swag@latest &&
      go mod download &&
      go mod tidy &&
      swag init -g cmd/flowcontrol/main.go --parseDependency --parseInternal &&
      air -c .air.toml"
    environment:
      - GO_ENV=development
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/go/cache
      - CONFIG_FILE=/app/config.json
      - CGO_ENABLED=1

  test:
    image: golang:1.22.9-bullseye
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - GO_ENV=test
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/go/cache
      - CGO_ENABLED=1
    command: sh -c "
      apt-get update && apt-get install -y sqlite3 libsqlite3-dev make git curl && 
      go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest &&
      go install github.com/swaggo/swag/cmd/swag@latest &&
      go mod download &&
      go mod tidy &&
      make"

volumes:
  go-cache: