services:
  dev:
    image: golang:1.22.1-bullseye
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go
    ports:
      - "8080:8080"
    networks:
      - flow-network
    command: sh -c "
      apt-get update && apt-get install -y sqlite3 libsqlite3-dev && 
      go install github.com/cosmtrek/air@v1.49.0 && 
      go install github.com/swaggo/swag/cmd/swag@latest &&
      go mod download &&
      go mod tidy &&
      cd /app &&
      swag init -g cmd/flowcontrol/main.go --parseDependency --parseInternal &&
      air -c .air.toml"
    environment:
      - GO_ENV=development
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/go/cache
      - CONFIG_FILE=/app/config.json
      - CGO_ENABLED=1
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  test:
    image: golang:1.22.1-bullseye
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go
    networks:
      - flow-network
    environment:
      - GO_ENV=test
      - GOMODCACHE=/go/pkg/mod
      - GOCACHE=/go/cache
      - CGO_ENABLED=1
      - CONFIG_FILE=/app/config.json
      - TEST_TIMEOUT=5m
      - TEST_FLAGS=-v -race -cover
      - PATH=/go/bin:${PATH}
    command: sh -c "
      apt-get update && apt-get install -y sqlite3 libsqlite3-dev make git curl && 
      go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest &&
      go install github.com/swaggo/swag/cmd/swag@latest &&
      go mod download &&
      go mod tidy &&
      cd /app &&
      mkdir -p data logs &&
      touch data/flows.db &&
      chmod -R 777 data logs &&
      tail -f /dev/null"

volumes:
  go-cache:

networks:
  flow-network:
    driver: bridge