name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-check:
    name: Docker Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Make scripts executable
      run: chmod +x scripts/*.sh scripts/**/*.sh

    - name: Check Docker environment
      run: make docker-check

    - name: Test Docker recovery
      run: make docker-test

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: docker-check

    steps:
    - uses: actions/checkout@v4

    - name: Make scripts executable
      run: chmod +x scripts/*.sh scripts/**/*.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run tests in Docker
      run: ./scripts/test.sh

  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: docker-check

    steps:
    - uses: actions/checkout@v4

    - name: Make scripts executable
      run: chmod +x scripts/*.sh scripts/**/*.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check formatting
      run: ./scripts/fmt.sh

    - name: Run linters
      run: ./scripts/lint.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
    - uses: actions/checkout@v4

    - name: Make scripts executable
      run: chmod +x scripts/*.sh scripts/**/*.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build in Docker
      run: ./scripts/build.sh 